language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

addons:
  apt:
    packages:
    - pylint
    - python-lxml
    - python3-lxml

# command to install dependencies
install: 
  - pip install nose
  - pip install -r requirements.txt

 
# command to run tests
script: 
  - pylint --rcfile=.pylint.rc eagle-tp-clearance.py
  - nosetests tests/
